// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515165752_Ratings1")]
    partial class Ratings1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripUser", b =>
                {
                    b.Property<int>("ParticipantTripsId")
                        .HasColumnType("int");

                    b.Property<int>("TravelersId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantTripsId", "TravelersId");

                    b.HasIndex("TravelersId");

                    b.ToTable("TripUser");
                });

            modelBuilder.Entity("backend.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gamta"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Plaukimas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Slidinėjimas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fotografija"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Maistas"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Muzika"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Skaitymas"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Istorija"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sportas"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Menas"
                        });
                });

            modelBuilder.Entity("backend.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SightId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SightId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("backend.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("EndingLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartingLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("backend.Models.RouteSight", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("SightId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("VisitOrder")
                        .HasColumnType("int");

                    b.HasKey("RouteId", "SightId");

                    b.HasIndex("SightId");

                    b.ToTable("RouteSights");
                });

            modelBuilder.Entity("backend.Models.Sight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CoordinateX")
                        .HasColumnType("float");

                    b.Property<double>("CoordinateY")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Arsenalo g. 5, Vilnius",
                            City = "Vilnius",
                            CoordinateX = 25.290299999999998,
                            CoordinateY = 54.686900000000001,
                            Description = "Simbolinė Vilniaus vieta su Gedimino bokštu ir nuostabia panorama.",
                            Duration = 3600,
                            FullDescription = "Gedimino kalnas – vienas svarbiausių Vilniaus simbolių. Ant kalno stūkso Gedimino pilies bokštas, iš kurio atsiveria nuostabi senojo Vilniaus panorama. Kalnas yra archeologinis, istorinis ir kultūrinis paminklas, pritraukiantis tūkstančius lankytojų kasmet.",
                            Name = "Gedimino kalnas",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/9/9d/Gedimino_pilis_by_Augustas_Didzgalvis.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Jurgaičių kaimas",
                            City = "Šiauliai",
                            CoordinateX = 23.4175,
                            CoordinateY = 56.0154,
                            Description = "Unikalus piligrimystės centras su tūkstančiais kryžių.",
                            Duration = 3600,
                            FullDescription = "Kryžių kalnas – vienas žinomiausių Lietuvos piligrimystės centrų, pritraukiantis tūkstančius lankytojų kasmet. Šis unikalus religinis kompleksas, kurį sudaro dešimtys tūkstančių kryžių, liudija lietuvių tautos tikėjimą ir pasiaukojimą. Vieta įtraukta į UNESCO paveldą.",
                            Name = "Kryžių kalnas",
                            PhotoUrl = "https://www.turistopasaulis.lt/wp-content/uploads/2013/10/kry%C5%BEi%C5%B3-kalnas-05.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kalnai parkas, Vilnius",
                            City = "Vilnius",
                            CoordinateX = 25.299199999999999,
                            CoordinateY = 54.688400000000001,
                            Description = "Monumentalus paminklas su nuostabia miesto panorama.",
                            Duration = 3600,
                            FullDescription = "Trijų kryžių kalnas – vienas populiariausių Vilniaus apžvalgos taškų. Ant kalno stovi trys balti betoniniai kryžiai, pastatyti 1989 metais vietoje 1916 m. pastatytų medinių kryžių. Nuo kalno atsiveria įspūdinga Vilniaus senamiestis panorama.",
                            Name = "Trijų kryžių kalnas",
                            PhotoUrl = "https://tobuladovana.lt/images/blog/5/triju-kryziu-kalnas.jpeg"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Karaimų g. 41, Trakai",
                            City = "Trakai",
                            CoordinateX = 24.934699999999999,
                            CoordinateY = 54.6524,
                            Description = "Vienas gražiausių Lietuvos pilių kompleksų, esantis saloje Galvės ežere.",
                            Duration = 7200,
                            FullDescription = "Trakų salos pilis – vienas iš labiausiai turistų lankomas objektų Lietuvoje. Ši XIV a. pabaigoje pastatyta gotinė pilis yra vienintelė vandeniu apsuptų pilių Rytų Europoje. Čia įsikūręs Trakų istorijos muziejus, vyksta įvairūs renginiai ir festivaliai.",
                            Name = "Trakų pilis",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/7/77/Traku_pilis_by_Augustas_Didzgalvis.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Puntuko akmens takas, Anykščiai",
                            City = "Anykščiai",
                            CoordinateX = 25.116700000000002,
                            CoordinateY = 55.533299999999997,
                            Description = "Didžiausias riedulys Lietuvoje, apipintas legendomis.",
                            Duration = 3600,
                            FullDescription = "Puntuko akmuo – didžiausias riedulys Lietuvoje, kurio tūris siekia 265 kubinių metrų. Šis unikalus gamtos paminklas apipintas daugybe legendų ir pasakojimų. Akmuo yra populiari turistų lankoma vieta Anykščių rajone.",
                            Name = "Puntuko akmuo",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/lt/b/b6/LT_Anyksciai_Puntukas_01.jpg"
                        });
                });

            modelBuilder.Entity("backend.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Mail = "jonas@example.com",
                            Username = "Jonas"
                        },
                        new
                        {
                            Id = 11,
                            Mail = "petras@example.com",
                            Username = "Petras"
                        },
                        new
                        {
                            Id = 12,
                            Mail = "ona@example.com",
                            Username = "Ona"
                        });
                });

            modelBuilder.Entity("backend.Models.UserInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("UserId", "InterestId")
                        .IsUnique();

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("TripUser", b =>
                {
                    b.HasOne("backend.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("ParticipantTripsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("TravelersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Rating", b =>
                {
                    b.HasOne("backend.Models.Sight", "Sight")
                        .WithMany("Ratings")
                        .HasForeignKey("SightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Route", b =>
                {
                    b.HasOne("backend.Models.Trip", "Trip")
                        .WithMany("Routes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("backend.Models.RouteSight", b =>
                {
                    b.HasOne("backend.Models.Route", "Route")
                        .WithMany("RouteSights")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Sight", "Sight")
                        .WithMany("RouteSights")
                        .HasForeignKey("SightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Sight");
                });

            modelBuilder.Entity("backend.Models.Trip", b =>
                {
                    b.HasOne("backend.Models.User", "Owner")
                        .WithMany("OwnedTrips")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("backend.Models.UserInterest", b =>
                {
                    b.HasOne("backend.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("backend.Models.Route", b =>
                {
                    b.Navigation("RouteSights");
                });

            modelBuilder.Entity("backend.Models.Sight", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("RouteSights");
                });

            modelBuilder.Entity("backend.Models.Trip", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("OwnedTrips");

                    b.Navigation("Ratings");

                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
