import type { Metadata } from 'next';
import './globals.css';
import { Outfit } from 'next/font/google';
import { Navbar } from '@/components/layout/NavBar';

const outfit = Outfit({
	subsets: ['latin'],
	weight: ['400', '600', '700'],
	variable: '--font-outfit',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={` ${outfit.variable} antialiased flex flex-col min-h-screen`}>
			<body className='flex-1 flex flex-col'>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
